export const movies = [
  {
    id: 1,
    titulo: "Harry Potter y la piedra filosofal",
    año: 2001,
    precioDolares: 14.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 100,
  },
  {
    id: 2,
    titulo: "Harry Potter y la cámara secreta",
    año: 2002,
    precioDolares: 15.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 80,
  },
  {
    id: 3,
    titulo: "Harry Potter y el prisionero de Azkaban",
    año: 2004,
    precioDolares: 16.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 120,
  },
  {
    id: 4,
    titulo: "Harry Potter y el cáliz de fuego",
    año: 2005,
    precioDolares: 17.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 90,
  },
  {
    id: 5,
    titulo: "Harry Potter y la Orden del Fénix",
    año: 2007,
    precioDolares: 18.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 110,
  },
  {
    id: 6,
    titulo: "Harry Potter y el misterio del príncipe",
    año: 2009,
    precioDolares: 19.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 70,
  },
  {
    id: 7,
    titulo: "Harry Potter y las Reliquias de la Muerte - Parte 1",
    año: 2010,
    precioDolares: 20.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 60,
  },
  {
    id: 8,
    titulo: "Harry Potter y las Reliquias de la Muerte - Parte 2",
    año: 2011,
    precioDolares: 21.99,
    caratulaURL: "https://1.bp.blogspot.com/-Swnw1F-qqms/XmUL5f-OekI/AAAAAAAAGxM/3PagZ_C_nxYw7DDzAKmZD1fQXud0VmXAwCLcBGAsYHQ/s1600/portada-harry-potter-y-la-piedra-filosofal-nueva-edicion-bolsillo-2020-libro-pdf.jpg",
    stock: 50,
  },
];
